RA-13 Implement recipe screen
ArtemMrtN/AndroidRecipesApp pull request #11
Opened 2024-12-15 16:33 UTC by ArtemMrtN

2024-12-15 18:21 UTC, Churickoid requested changes

2024-12-15 18:21 UTC, Churickoid commented on app/src/main/res/layout/item_ingrediens.xml
> +    </LinearLayout>
Каждая лишняя вложенность - дополнительная нагрузка на устройство при генерации макета. Сам item не такой сложный, можно сделать рутовую view - LinearLayout, основной текст по ширине 0dp с width = 1, а остальные текстВьюхи - по ширине wrapContent

2024-12-15 18:21 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:layout_marginBottom="20dp"
Вынести в ресурсы

2024-12-15 18:21 UTC, Churickoid commented on gradle/libs.versions.toml
> +material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
У тебя уже есть подключенная либа om.google.android.material, в этой точно есть смысл?

2024-12-16 07:08 UTC, ArtemMrtN commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:layout_marginBottom="20dp"
Это случайно подвинулось))

2024-12-16 07:15 UTC, ArtemMrtN commented on gradle/libs.versions.toml
> +material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
Затупил

2024-12-16 09:53 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-12-16 09:53 UTC, Churickoid commented on app/src/main/res/layout/item_ingrediens.xml
> +        tools:text="Творог" />
Сюда бы еще добавить margin, чтоб текст не склеивался с количеством порций

2024-12-16 11:33 UTC, merged