RA-23 Receive recipe in VM
ArtemMrtN/AndroidRecipesApp pull request #19
Opened 2024-12-25 08:59 UTC by ArtemMrtN

2024-12-25 19:25 UTC, Churickoid requested changes

2024-12-25 19:25 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/FavoritesFragment.kt
> +        val bundle = Bundle().apply { putInt(RECIPE_ID, recipeId) }
У тебя до этого была такого типа конструкция, которая выглядит более чистой. В ней также можно поменять  на RECIPE_ID to recipeId
val bundle = bundleOf(ARG_RECIPE to recipe)

2024-12-25 19:25 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/RecipeFragment.kt
> +            viewModel.onFavoritesClicked(favoritesId.any { it.toIntOrNull() == recipe.id })
Принцип MVVM такой, что фрагмент ничего не знает о том как меняются данные в стейте ViewModel и что внутри ViewModel происходит вообще. Сейчас же всем управляет фрагмент, просто он вызывает нужные функцие viewModel, никакого MVVM по сути и нет.
Что нужно сделать:
 Фрагмент должен содержать в себе по минимуму работы с какими либо данными. То есть должен быть принцип черного ящика. При нажатии на иконку, мы вызываем только viewModel.onFavoritesClicked, триггирим вьюМодель на действие. Далее всё выполняется под копотом ViewModel и фрагмент больше ничего не дергает. Потом viewModel кладёт результат в стейт. Всё что написано внутри viewModel.state.observe(viewLifecycleOwner) триггерится каждый раз, когда меняется стейт вьюМодели. Поэтому мы должны перенести всю логику отрисовки для кнопки внутрь observer. А всё сохранение-удаление делает viewModel

2024-12-26 14:15 UTC, Churickoid requested changes

2024-12-26 14:15 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/RecipeFragment.kt
> +            viewModel.state.observe(viewLifecycleOwner) { state ->
Ты уже выше подписался viewModel.state.observe, больше подписываться не надо. А так при каждом клике будет создаваться новый слушатель и кнопка будет обновляться 1+количество кликов, такого не надо. Достаточно одного слушателя

2024-12-26 14:15 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/recipes/recipe/RecipeViewModel.kt
> +            _state = MutableLiveData(RecipeState().copy(
Не нужно создавать новую liveData, нужно менять лишь её value. Иначе все подпищики сотрутся при замене данных. В .copy нет никакого смысла, поскольку копируется дефолтное значение стейта, а не последнее текущее значение. Нужно копировать последний актуальный стейт

2024-12-27 09:17 UTC, Churickoid requested changes

2024-12-27 09:17 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/RecipeFragment.kt
> +                binding.iconFavorites.setImageResource(R.drawable.ic_heart_empty)
Здесь менять ничего не надо, только вызываем один метод viewModel. Далее принцип черного ящика, фрагмент ничего не знает что делает viewModel. Она получает результат внутри viewModel.state.observe(viewLifecycleOwner) { state ->
            Log.i("!!!", "isFavorite: ${state.isFavorites}")
            if (state.isFavorites) {
                binding.iconFavorites.setImageResource(R.drawable.ic_heart)
            } else {
                binding.iconFavorites.setImageResource(R.drawable.ic_heart_empty)
            }
        }
        и по актуальному стейту отрисовывает UI. 
        
        Дергаем один метод viewModel -> она внутри делает свою логику и меняет стейт внутри LiveData -> На liveData мы подписались во фрагменте через observer -> при изменении каждого стейта будет триггерится код внутри observer. И по итогу весь динамический UI должен меняться внутри observer толкьо, а не быть разрабросанным по всему фрагменту

2024-12-27 09:20 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/ui/recipes/recipe/RecipeViewModel.kt
> +//            )
коммент этот надо убать

2024-12-27 09:48 UTC, ArtemMrtN commented on app/src/main/java/com/mrt/androidrecipesapp/ui/RecipeFragment.kt
> +                binding.iconFavorites.setImageResource(R.drawable.ic_heart_empty)
Механизм я так и понял) Но не до конца похоже) Сама механика очень крутая, постараюсь разобраться получше

2024-12-27 10:38 UTC, Churickoid approved these changes

2024-12-27 13:43 UTC, merged