RA-04 Create first fragment
ArtemMrtN/AndroidRecipesApp pull request #2
Opened 2024-12-03 08:56 UTC by ArtemMrtN

2024-12-03 15:55 UTC, Churickoid requested changes

2024-12-03 15:55 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/MainActivity.kt
> +        transaction.commit()
Ты используешь Java метод replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add<>() из класса FragmentTransaction.kt.

Именно для импорта метода replace нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-12-03 15:55 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/CategoriesListFragment.kt
> +        return view
Сейчас вынесение в отдельную переменную выглядит лишним, почему бы сразу не писать return binding.root

2024-12-03 15:55 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/CategoriesListFragment.kt
> +    private val binding get() = _binding!!
!! – оператор-утверждение "это не null" . Как я упоминал ранее – это опасный оператор и не рекомендуется его использовать, тк если в переменную все же придет null – приложение крашнется.

Это отрицательно повлияет на пользовательский опыт и сразу без дебага будет сложно найти причину вылета приложения. Устройств на андройд (и версий андройд) множество, далеко не все работают идеально, как наши собственные или эмулятор. Поэтому, чтобы меньше было проблем в будущем, подкладываем солому заранее. А именно добавляя разные безопасные обработчики.

В уроке реализовывался backing property (резервное свойство). Предлагаю его добавить сюда

2024-12-03 15:55 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
lateinit также не рекомендуется использовать, при неправильном обращении приложение будет падатью Предлагаю здесь тоже реализовать backing property

2024-12-04 07:24 UTC, ArtemMrtN commented on app/src/main/java/com/mrt/androidrecipesapp/MainActivity.kt
> +        transaction.commit()
Что-то я похоже в описании задачи запутался. В итоге не тот метод нагуглил)

2024-12-04 07:26 UTC, ArtemMrtN commented on app/src/main/java/com/mrt/androidrecipesapp/CategoriesListFragment.kt
> +    private val binding get() = _binding!!
Помню про !!, но в документации было так написано, решил повторить. Буду более критично относится к документациям

2024-12-04 14:55 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-12-04 15:49 UTC, merged