RA-07 screen with a list of categories
ArtemMrtN/AndroidRecipesApp pull request #5
Opened 2024-12-06 12:16 UTC by ArtemMrtN

2024-12-06 19:49 UTC, Churickoid requested changes

2024-12-06 19:49 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +
Когда ты добавил атрибут tools:listitem="@layout/item_category",  на превьюхе в студии отображаются сверстанные карточки категории.

Карточку надо сверстать. Представь, что элемент списка – это весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools. По итогу список на фрагменте должен соответстовать дизайну из фигмы, только с данными-заглушками

2024-12-06 19:49 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_height="224dp">
Это значение тоже нужно вынести в dimens

2024-12-07 05:14 UTC, ArtemMrtN commented on app/src/main/res/layout/item_category.xml
> +
Из задачи я подумал, что это будет в следующей стори, поэтому не стал делать. Сейчас исправлю

2024-12-07 20:40 UTC, Churickoid approved these changes
Молодец, всё верно! Поправь мелкий коммент в следующем пр

2024-12-07 20:40 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_marginStart="@dimen/margin_half"/>
Текст заголовка будет справа прижиматься к краю, добавь марджин справа

2024-12-08 08:19 UTC, merged