RA-09 Pass callback
ArtemMrtN/AndroidRecipesApp pull request #7
Opened 2024-12-10 07:33 UTC by ArtemMrtN

2024-12-10 07:34 UTC, ArtemMrtN commented
Не пойму на этом этапе должен уже работать переход в категорию или пока нет?

2024-12-10 16:17 UTC, Churickoid requested changes

2024-12-10 16:17 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/CategoriesListAdapter.kt
> +        val itemClickListener = listener
На текущем этапе переход должен работать. Сейчас он не происходит, поскольку ты присваиваешь значение локальной переменной, а не this.itemClickListener

2024-12-11 14:07 UTC, Churickoid approved these changes
Молодец, по заданию верно! Поправь в следующем ПР коммент по оформлению

2024-12-11 14:07 UTC, Churickoid commented on app/src/main/java/com/mrt/androidrecipesapp/CategoriesListFragment.kt
> +            .commit()
Опять используешь старый метод навигации, в другиз заданиях мы уже делали через commit{
`replace<MyFragment>()`
}

2024-12-11 14:25 UTC, merged